const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  startOAuthFlow: () => ipcRenderer.invoke('start-oauth-flow'),
  checkAuth: () => ipcRenderer.invoke('check-auth'),
  fetchEmails: (incremental) => ipcRenderer.invoke('fetch-emails', incremental),
  fetchFullEmail: (emailId) => ipcRenderer.invoke('fetch-full-email', emailId),
  getEmailDetail: (emailId) => ipcRenderer.invoke('get-email-detail', emailId),
  getEmailStats: () => ipcRenderer.invoke('get-email-stats'),
  getEmailsByDate: () => ipcRenderer.invoke('get-emails-by-date'),
  getSendersStats: () => ipcRenderer.invoke('get-senders-stats'),
  getHourlyDistribution: () => ipcRenderer.invoke('get-hourly-distribution'),
  searchEmails: (query, filters) => ipcRenderer.invoke('search-emails', query, filters),
  analyzeEmails: () => ipcRenderer.invoke('analyze-emails'),
  submitPrompt: (prompt) => ipcRenderer.invoke('submit-prompt', prompt),
  logout: () => ipcRenderer.invoke('logout'),
  saveDashboardWidgets: (widgets) => ipcRenderer.invoke('save-dashboard-widgets', widgets),
  getDashboardWidgets: () => ipcRenderer.invoke('get-dashboard-widgets'),
  getJobApplications: () => ipcRenderer.invoke('get-job-applications'),
  addJobApplication: (app) => ipcRenderer.invoke('add-job-application', app),
  updateJobApplication: (id, app) => ipcRenderer.invoke('update-job-application', id, app),
  deleteJobApplication: (id) => ipcRenderer.invoke('delete-job-application', id),
  analyzeJobApplications: () => ipcRenderer.invoke('analyze-job-applications'),
  scanJobEmails: () => ipcRenderer.invoke('scan-job-emails'),
  getDashStats: () => ipcRenderer.invoke('get-dash-stats'),
  getDailyVolume: (days) => ipcRenderer.invoke('get-daily-volume', days),
  exportData: (format) => ipcRenderer.invoke('export-data', format),
  exportJobApplications: (format) => ipcRenderer.invoke('export-job-applications', format),
  getAiInsights: () => ipcRenderer.invoke('get-ai-insights'),
  generateProactiveInsights: () => ipcRenderer.invoke('generate-proactive-insights'),
  getTrainingData: () => ipcRenderer.invoke('get-training-data'),
  saveTrainingData: (type, data) => ipcRenderer.invoke('save-training-data', type, data),
  fetchCalendarEvents: () => ipcRenderer.invoke('fetch-calendar-events'),
  getCalendarEvents: (dateFrom, dateTo) => ipcRenderer.invoke('get-calendar-events', dateFrom, dateTo),
  getCalendarCorrelation: () => ipcRenderer.invoke('get-calendar-correlation'),
  onEmailsSynced: (callback) => ipcRenderer.on('emails-synced', (_event, data) => callback(data)),
});
